#######################################################################################
name: Rcx
on:
  push:
    paths:
      - 'Records/RcloneFlow.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 #############################################################################################
       - name: Checkout
         uses: actions/checkout@main    
   #   - uses: actions/checkout@master 
 #############################################################################################      
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://Ratskjds:${{ secrets.github.token }}@github.com" > ~/.git-credentials
#############################################################################################  
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}
#############################################################################################
       - name: Deploying and Running rclone
         timeout-minutes: 330
         continue-on-error: true
         uses: tsexr7hxyf/rc-backend@main
         env:
           RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
         with:
           args: copy "smalltd:" "drive1e:" --stats 30s --transfers 5 --checkers 5 -P --ignore-existing --drive-chunk-size 16M --onedrive-chunk-size=5M --dropbox-chunk-size 16M --drive-acknowledge-abuse --drive-server-side-across-configs --drive-stop-on-upload-limit
 #############################################################################################
       - name: Send Record to Github
         continue-on-error: true
         run: |
              git clone https://github.com/Ratskjds/botflow
              cd botflow || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> Records/RcloneFlow.txt
              git add Records/RcloneFlow.txt
              git commit -m "Workflow : add recorded loop to logs $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/Ratskjds/botflow HEAD:main
#############################################################################################
